name: tag-release
on:
  push
    # Tag a release upon pushing code to the master branch
    # branches:
    #   - master
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.52.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          DRY_RUN: true

      - run: echo "${{ steps.tag.outputs.new_tag }}"